name: Java CI/CD with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Init build log
        run: echo "=== Build job start $(date -u) ===" > build.log

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'gradle'

      - name: Ensure Gradle wrapper
        run: |
          set -euo pipefail
          {
            test -f gradlew || { echo "[build] ERROR: gradlew missing in repo"; exit 1; }
            ./gradlew --version
          } |& tee -a build.log

      - name: Build (bootJar)
        run: |
          set -o pipefail
          ./gradlew --no-daemon bootJar |& tee -a build.log

      - name: List JARs to upload
        run: |
          set -o pipefail
          {
            echo "[build] Listing candidate JARs under **/build/libs/"
            find . -path '*/build/libs/*.jar' -type f -print
          } |& tee -a build.log

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: |
            **/build/libs/*.jar
            build.log
          if-no-files-found: error

      - name: Install jq (for reporter)
        if: failure()
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Report failure to Rooty (logs + git diff)
        if: failure()
        env:
          REPORT_URL: ${{ secrets.CI_REPORT_URL }}
          REPORT_TOKEN: ${{ secrets.ROOTY_API_KEY }}
        run: |
          set -euo pipefail

          if [[ ! -s build.log ]]; then
            echo "[reporter] Build failed but no logs captured." > build.log
          fi

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE="${{ github.event.pull_request.base.sha }}"
            HEAD="${{ github.event.pull_request.head.sha }}"
          else
            BASE="${{ github.event.before }}"
            HEAD="${{ github.sha }}"
          fi
          [[ -n "${BASE:-}" ]] || BASE="$(git rev-parse HEAD^ 2>/dev/null || echo '')"
          [[ -n "${HEAD:-}" ]] || HEAD="$(git rev-parse HEAD)"

          git diff --no-color --unified=0 "$BASE...$HEAD" > ci.diff || true
          touch ci.diff

          ERROR_LOGS_JSON="$(tail -n 400 build.log | jq -Rcs 'split("\n") | map(select(length>0)) | .[-400:]')"
          TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

          payload=$(jq -n \
            --arg workflowName "${{ github.workflow }}" \
            --arg jobName "${{ github.job }}" \
            --arg repository "${{ github.repository }}" \
            --arg commitSha "${{ github.sha }}" \
            --arg timestamp "$TIMESTAMP" \
            --rawfile diff ci.diff \
            --argjson errorLogs "$ERROR_LOGS_JSON" \
            '{workflowName:$workflowName, jobName:$jobName, errorLogs:$errorLogs, gitDiff:$diff, repository:$repository, commitSha:$commitSha, timestamp:$timestamp}')

          CURL_HEADERS=(-H "Content-Type: application/json")
          [[ -n "${REPORT_TOKEN:-}" ]] && CURL_HEADERS+=(-H "Authorization: ApiKey $REPORT_TOKEN")
          curl -sS -X POST "$REPORT_URL" "${CURL_HEADERS[@]}" -d "$payload" | cat

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init deploy log
        run: echo "=== Deploy job start $(date -u) ===" > deploy.log

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: dist

      - name: List downloaded files
        run: |
          set -o pipefail
          {
            echo "[deploy] Listing files under dist/"
            find dist -maxdepth 5 -type f -print
          } |& tee -a deploy.log

      - name: Pick JAR path
        id: pick
        shell: bash
        run: |
          set -euo pipefail
          {
            echo "[pick] Resolving JAR under dist/..."
            JAR="$(find dist -type f -name '*.jar' | head -n1 || true)"
            if [[ -z "${JAR}" ]]; then
              echo "[pick][ERROR] No JAR found under dist/."
              echo "[pick] Tree snapshot:"
              (cd dist && find . -maxdepth 5 -type f -print || true)
              exit 1
            fi
            echo "[pick] JAR=${JAR}"
            echo "jar=${JAR}" >> "$GITHUB_OUTPUT"
          } |& tee -a deploy.log

      - name: Install jq (for reporter)
        run: sudo apt-get update |& tee -a deploy.log && sudo apt-get install -y jq |& tee -a deploy.log

      - name: SCP Transfer (capture log)
        timeout-minutes: 0.1
        env:
          PORT: ${{ secrets.PORT }}
          USER: ${{ secrets.USER }}
          SERVER: ${{ secrets.SERVER_IP_ADDRESS }}
        run: |
          set -o pipefail
          scp -P "$PORT" "${{ steps.pick.outputs.jar }}" "$USER@$SERVER:/home/ubuntu/LSA_release" |& tee -a deploy.log

      - name: Restart server (append log)
        timeout-minutes: 1
        env:
          PORT: ${{ secrets.PORT }}
          USER: ${{ secrets.USER }}
          SERVER: ${{ secrets.SERVER_IP_ADDRESS }}
        run: |
          set -o pipefail
          ssh -p "$PORT" "$USER@$SERVER" 'sudo systemctl restart LSAServer.service' |& tee -a deploy.log

      - name: Report failure to Rooty (logs + git diff)
        if: failure()
        env:
          REPORT_URL: ${{ secrets.CI_REPORT_URL }}
          REPORT_TOKEN: ${{ secrets.ROOTY_API_KEY }}
        run: |
          set -euo pipefail

          if [[ ! -s deploy.log ]]; then
            echo "[reporter] Deploy failed but no logs captured." > deploy.log
          fi

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BASE="${{ github.event.pull_request.base.sha }}"
            HEAD="${{ github.event.pull_request.head.sha }}"
          else
            BASE="${{ github.event.before }}"
            HEAD="${{ github.sha }}"
          fi
          [[ -n "${BASE:-}" ]] || BASE="$(git rev-parse HEAD^ 2>/dev/null || echo '')"
          [[ -n "${HEAD:-}" ]] || HEAD="$(git rev-parse HEAD)"

          git diff --no-color --unified=0 "$BASE...$HEAD" > ci.diff || true
          touch ci.diff

          ERROR_LOGS_JSON="$(tail -n 400 deploy.log | jq -Rcs 'split("\n") | map(select(length>0)) | .[-400:]')"
          TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

          payload=$(jq -n \
            --arg workflowName "${{ github.workflow }}" \
            --arg jobName "${{ github.job }}" \
            --arg repository "${{ github.repository }}" \
            --arg commitSha "${{ github.sha }}" \
            --arg timestamp "$TIMESTAMP" \
            --rawfile diff ci.diff \
            --argjson errorLogs "$ERROR_LOGS_JSON" \
            '{workflowName:$workflowName, jobName:$jobName, errorLogs:$errorLogs, gitDiff:$diff, repository:$repository, commitSha:$commitSha, timestamp:$timestamp}')

          CURL_HEADERS=(-H "Content-Type: application/json")
          [[ -n "${REPORT_TOKEN:-}" ]] && CURL_HEADERS+=(-H "Authorization: ApiKey $REPORT_TOKEN")
          curl -sS -X POST "$REPORT_URL" "${CURL_HEADERS[@]}" -d "$payload" | cat
